{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "filters", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Choice", "config": {"name": "kernel_size", "default": 2, "conditions": [], "values": [2, 3, 5], "ordered": true}}, {"class_name": "Choice", "config": {"name": "pool_size", "default": 2, "conditions": [], "values": [2, 3], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout_conv", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "units1", "default": 64, "conditions": [], "values": [64, 128, 256], "ordered": true}}, {"class_name": "Choice", "config": {"name": "units2", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout1", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout2", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "lr", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"filters": 128, "kernel_size": 5, "pool_size": 3, "dropout_conv": 0.4, "units1": 64, "units2": 32, "dropout1": 0.30000000000000004, "dropout2": 0.4, "lr": 0.01}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n            ^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\giakh\\AppData\\Local\\Temp\\ipykernel_18920\\2825404103.py\", line 41, in build_model_hp\n    return build_cnn_lstm(\n           ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\giakh\\AppData\\Local\\Temp\\ipykernel_18920\\2825404103.py\", line 12, in build_cnn_lstm\n    model = Sequential([\n            ^^^^^^^^^^^^\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras\\src\\models\\sequential.py\", line 76, in __init__\n    self._maybe_rebuild()\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras\\src\\models\\sequential.py\", line 149, in _maybe_rebuild\n    self.build(input_shape)\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras\\src\\layers\\layer.py\", line 229, in build_wrapper\n    original_build_method(*args, **kwargs)\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras\\src\\models\\sequential.py\", line 195, in build\n    x = layer(x)\n        ^^^^^^^^\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\giakh\\miniconda3\\envs\\ai_train\\Lib\\site-packages\\keras\\src\\ops\\operation_utils.py\", line 221, in compute_conv_output_shape\n    raise ValueError(\nValueError: Computed output size would be negative. Received `inputs shape=(None, 1, 14)`, `kernel shape=(5, 14, 128)`, `dilation_rate=[1]`.\n"}